### ISSUE TITLE
DateTimeImmutable mapping throws error when target side already have value

### ISSUE THREAD

**Issue by gabplch** [rekalogika/mapper#88] opened 2024-08-23 13:53 UTC
There is an error, while I'm trying to map DateTimeImmutable from dto to the model, as [DateTimeTransformer](https://github.com/rekalogika/mapper/blob/fb8f25ab805b66b4d9495c5c0e3578ea1da465e5/src/Transformer/Implementation/DateTimeTransformer.php#L47) supports only \DateTime class

**e.g. of error:**
```
{
    "message": "Target must be null unless it is a DateTime, \"DateTimeImmutable\" given Mapping path: \"date\"."
}
```

**Reproducing example:**
```php
ClassA {
        public ?\DateTimeImmutable $date;
}

ClassADto {
       public ?\DateTimeImmutable $date;
}

**...**

$classA = new ClassA();
$classA->date = new \DateTimeImmutable('-1 month');

$classADto = new ClassADto();
$classADto->date = new \DateTimeImmutable();

$mapper->map(classADto, $classA);

```

**Comment by priyadi** [comment] 2024-08-24 04:12
I botched your PR, sorry about that. But the issue is fixed in https://github.com/rekalogika/mapper/pull/91 . I decided to just remove the null check on the target side. Thank you for your contribution.

**Closed by priyadi** 2024-08-24 04:12 UTC
